---
title: "play_visual"
author: "Richard Barad"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(lubridate)
library(tidycensus)
library(viridis)
library(gridExtra)
library(ggspatial)
library(tigris)

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))
```


```{r cars}
B_Jun2023 <- read.csv('./Data/202306-bluebikes-tripdata.csv')
B_Jul2023 <- read.csv('./Data/202307-bluebikes-tripdata.csv')

Data <- rbind(B_Jun2023,B_Jul2023) %>%
  mutate(start_station_name = ifelse(start_station_name == 'Graham and Parks School – Linnaean St at Walker St','Graham and Parks School',start_station_name)) 

bike_data <- read.csv('./Data/current_bluebikes_stations.csv') %>%
  filter(District != 'Salem' & Name != 'BCBS Hingham') %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs='EPSG:4326') %>% st_transform('EPSG:2249')
  

rm(B_Jun2023)
rm(B_Jul2023)
```


```{r read_towns_data_MA, results='hide', warning=FALSE, message=FALSE}
MA_towns <- st_make_valid(st_read('https://arcgisserver.digital.mass.gov/arcgisserver/rest/services/AGOL/Census2020_Towns/MapServer/2/query?where=1%3D1&f=geojson')) %>% st_transform('EPSG:2249')

towns_filt <- MA_towns[st_is_within_distance(st_centroid(MA_towns),bike_data,10000) %>% lengths > 0,] %>%
  mutate(town = str_extract(NAMELSAD20, "\\w+"))

parks <- st_read('https://arcgisserver.digital.mass.gov/arcgisserver/rest/services/AGOL/OpenSpaceLevProt/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=%7Bxmin%3A+-70.99%2C+ymin%3A+42.43%2C+xmax%3A+-71.18%2C+ymax%3A+42.3%7D&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson')
```

```{r pressure, fig.width=12}


towns_filt2 <- towns_filt %>% st_transform('EPSG:4326') %>% st_crop(xmin= -70.99, xmax=-71.18, ymin=42.43,ymax=42.3) %>% st_transform('EPSG:2249') 


parks <- parks %>% st_transform('EPSG:2249') %>% st_intersection(.,towns_filt2)

bikes_filt2 <- bike_data[st_intersects(bike_data,towns_filt2) %>% lengths > 0,] 

bbox = st_bbox(towns_filt2)

towns_no_water <- towns_filt2 %>% erase_water()

play <- Data %>%
  mutate(day = as.character(floor_date(ymd_hms(started_at), unit = "day"))) %>%
  filter(day == '2023-07-10'| day == '2023-07-11' | day == '2023-07-12' | day == '2023-07-13' | day == '2023-07-14' | day == '2023-07-15') %>%
  group_by(start_station_name, end_station_name) %>%
  tally() %>%
  ungroup() %>%
  filter(n > 1) %>%
  filter(start_station_name != end_station_name) %>%
  left_join(bike_data %>% dplyr::select(Name, geometry), by = c("start_station_name" = "Name")) %>%
  st_as_sf() %>%
  mutate(start_lat = st_coordinates(geometry)[,2],
         start_long = st_coordinates(geometry)[,1]) %>%
  st_drop_geometry() %>%
  left_join(bike_data %>% dplyr::select(Name, geometry), by = c("end_station_name" = "Name")) %>%
  st_as_sf() %>%
  mutate(end_lat = st_coordinates(geometry)[,2],
         end_long = st_coordinates(geometry)[,1]) %>%
  st_drop_geometry() %>%
  arrange(n)

ggplot()+
  geom_rect(aes(xmin= bbox$xmin, xmax= bbox$xmax, ymin= bbox$ymin, ymax = bbox$ymax),fill='#c2d4fc')+
  geom_sf(data=towns_no_water,color="transparent",fill='grey70')+
  geom_sf(data=parks,fill='#c2fcd5',color='transparent',alpha=0.5)+
  geom_sf(data=towns_filt2,fill="transparent",color='grey30')+
  geom_segment(data=play,aes(x=start_long,y=start_lat,xend=end_long,yend=end_lat,alpha=n,color=n,linewidth=n))+
  scale_color_viridis(direction=-1)+
  labs(color='Number of Trips',fill='')+
  geom_sf(data=bikes_filt2,size=1,color='lightyellow')+
  geom_sf_text(data = towns_filt2,aes(label=town),size=3.5,position='jitter',color='white')+
  scale_alpha(range = c(0.2,1),guide = "none")+
  scale_linewidth(range = c(0.4,1),guide = "none")+
  ggtitle("Number of Bike Trips on July 12th 2023")+
  scale_x_continuous(limits = c(bbox$xmin, bbox$xmax)) +
  scale_y_continuous(limits = c(bbox$ymin, bbox$ymax))+
  theme(legend.position = c(0.85, 0.24), 
        legend.background = element_rect(fill="transparent", colour ="transparent"))+
  mapTheme
```
